# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-12 07:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diseasepredic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='combination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diseaseid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diseasepredic.Diseases')),
                ('symptomid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diseasepredic.Symptoms')),
            ],
        ),
    ]
