# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-12 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseasepredic', '0002_combination'),
    ]

    operations = [
        migrations.AddField(
            model_name='combination',
            name='name',
            field=models.CharField(default='feel', max_length=250),
            preserve_default=False,
        ),
    ]
